### PR TITLE
Fix the possible loss of precision when the key is Uint64 or Int64

### PR DESCRIPTION
**Pull request by jdhxyy**

### CODE REVIEW

**Comment by huandu** [comment]
You should update `calcScore()` instead of `compareTypes`.

**Comment by jdhxyy** [comment]
calcScore() return value is float64.For example,if key is 1311768465173141112,float64(1311768465173141112) = 1.311768465173141e+18,last three digit accuracy is loss

**Comment by jdhxyy** [comment]
so key 1311768465173141112 and 1311768465173141113 is same key for skiplist

**Comment by huandu** [comment]
You are right. Will you submit another PR for this issue?

**Comment by jdhxyy** [comment]
ok

**Pull request closed without merging**
